```sh
all identifiers of the C++ standard library are defined in a namespace called std

you have three options when using an identifier of the C++ standard library
1. You can qualify the identifier directly. For example, std::cout
2. You can use a using declaration. For example, using std::cout;
3. You can use a using directive. using namespace std;

C header files now have the new prefix c instead of the old extension .h:
#include <cstdlib>    // was: <stdlib.h>
#include <cstring>    // was: <string.h>
```

```sh
All exceptions thrown by the language or the library are derived from the base class exception, defined in <exception>.

These standard exception classes can be divided into three groups:
1. Language support
2. Logic errors
3. Runtime errors
Logic errors usually can be avoided because the reason is inside the scope of a program, such as a precondition violation. Runtime exceptions are caused by a reason that is outside the scope of the program, such as not enough resources.

Exceptions for language support are used by language features.
These exceptions are thrown when the following operations fail:
1. An exception of class bad_cast, defined in <typeinfo>, is thrown by the dynamic_cast operator if a type conversion on a reference fails at runtime.
2. An exception of class bad_typeid, defined in <typeinfo>, is thrown by the typeid operator for runtime type identification. If the argument to typeid is zero or the null pointer, this exception gets thrown.
3. An exception of class bad_exception, defined in <exception>, is used to handle unexpected exceptions. It can be thrown by the function unexpected(), which is called if a function throws an exception that is not listed in an exception specification Note, however, that the use of exception specifications is deprecated since C++11

Exception Classes for Logic Errors.
The C++ standard library provides the following classes for logic errors:
1. An exception of class invalid_argument is used to report invalid arguments, such as when a bitset (array of bits) is initialized with a char other than ’0’ or ’1’.
2. An exception of class length_error is used to report an attempt to do something that exceeds a maximum allowable size, such as appending too many characters to a string.
3. An exception of class out_of_range is used to report that an argument value is not in the expected range, such as when a wrong index is used in an array-like collection or string.
4. An exception of class domain_error is used to report a domain error.
5. Since C++11, an exception of class future_error is used to report logical errors when using asynchronous system calls (see Chapter 18). Note that runtime errors in this domain are raised via class system_error.
In general, classes for logic errors are defined in <stdexcept>. However, class future_error is defined in <future>.

Exception Classes for Runtime Errors.
Exceptions derived from runtime_error are provided to report events that are beyond the scope of a program and are not easily avoidable. The C++ standard library provides the following classes for runtime errors:
1. An exception of class range_error is used to report a range error in internal computations. In the C++ standard library, the exception can occur since C++11 in conversions between wide strings and byte strings.
2. An exception of class overflow_error is used to report an arithmetic overflow. In the C++ standard library the exception can occur if a bitset is converted into an integral value.
3. An exception of class underflow_error is used to report an arithmetic underflow.
4. Since C++11, an exception of class system_error is used to report errors caused by the underlying operating system. In the C++ standard library, this exception can be thrown in the context of concurrency, such as class thread, classes to control data races, and async().
5. An exception of class bad_alloc, defined in <new>, is thrown whenever the global operator new fails, except when the nothrow version of new is used. This is probably the most important runtime exception because it might occur at any time in any nontrivial program.
Since C++11, bad_array_new_length, derived from bad_alloc, will be thrown by new if
the size passed to new is less than zero or such that the size of the allocated object would exceed the implementation-defined limit (that is, if it’s a logic error rather than a runtime error).
6. An exception of class bad_weak_ptr, defined in <memory>, is thrown whenever the creation of a weak pointer out of a shared pointer fails.
7. An exception of class bad_function_call, defined in <functional>, is thrown whenever a function wrapper object gets invoked but has no target.
In addition, for the I/O part of the library, a special exception class called ios_base::failure is provided in <ios>. An exception of this class may be thrown when a stream changes its state due to an error or end-of-file. Since C++11, this class is derived from system_error;
Conceptionally, bad_alloc can be considered a system error. However, for historical reasons and because of its importance, implementations are encouraged to throw a bad_alloc rather than a system_error exception if an error represents an out-of-memory condition.
In general, classes for runtime errors are defined in <stdexcept>. Class system_error, however, is defined in <system_error>.

The exception classes are defined in many different header files. Thus, to be able to deal with all exceptions the library might throw, you have to include:
#include <exception>    // for classes exception and bad_exception
#include <stdexcept>    // for most logic and runtime error classes
#include <system_error>    // for system errors (since C++11)
#include <new>    // for out-of-memory exceptions
#include <ios>    // for I/O exceptions
#include <future>    // for errors with async() and futures (since C++11)
#include <typeinfo>    // for bad_cast and bad_typeid

For all standard exception classes, only one member can be used to get additional information besides the type itself: the virtual member function what(), which returns a null-terminated byte string:
```
![](/images/stl_1.png)
